name 'kreczko-apelpublisher'
version '0.0.1'

author 'kreczko'
license 'Apache License, Version 2.0'
project_page 'https://github.com/HEP-Puppet'
source 'git@github.com:HEP-Puppet/puppet-apelpublisher.git'
summary 'A Puppet module for the installation and setup of a Apel publisher'
description 'A Puppet module for the installation and setup of a Apel publisher'
dependency 'puppetlabs/mysql', '>=0.6.1'
dependency 'kreczko/yumhelper', '==0.0.1'
